/* Ejecutar configurar() con la cuenta mirlacolada@gmail.com.
   Establecer SHARED_SECRET en Propiedades del script antes de publicar.
   Publicar como aplicación web: ejecutar como propietario, acceso cualquiera.
   Guardar URL /exec y el mismo secreto en los secretos del sitio.
   Los comprobantes y la hoja permanecen privados. */
const MAIL='mirlacolada@gmail.com';
const HEADERS=['Fecha','ID','Nombre','Apellido','Cedula','Telefono','Correo','Metodo','Plan','Total','Abono','Saldo','Tasa BCV','Fecha tasa','Monto Bs','Promociones WhatsApp','Estado','Referencia','Comprobante','Token','Gift','Beneficiario','Cedula beneficiario'];
function configurar(){const p=PropertiesService.getScriptProperties();if(!p.getProperty('SHARED_SECRET'))throw Error('Define SHARED_SECRET en las propiedades del script.');let s;if(!p.getProperty('SHEET_ID')){s=SpreadsheetApp.create('MODO CREADOR - Inscripciones 2026');p.setProperty('SHEET_ID',s.getId());const t=s.getSheets()[0];t.setName('Inscripciones');t.appendRow(HEADERS);t.setFrozenRows(1);t.getRange(1,1,1,HEADERS.length).setFontWeight('bold').setBackground('#7929df').setFontColor('#ffffff');t.getRange('Q2:Q').setDataValidation(SpreadsheetApp.newDataValidation().requireValueInList(['pendiente_pago','en_revision','reservado','confirmado','rechazado'],true).build());t.hideColumns(20);}
if(!p.getProperty('FOLDER_ID')){const f=DriveApp.createFolder('MODO CREADOR - Comprobantes 2026');p.setProperty('FOLDER_ID',f.getId());}console.log('Configuración creada. Revisa la hoja y la carpeta en tu Drive.');}
function doPost(e){const lock=LockService.getScriptLock();try{const data=JSON.parse(e.postData.contents);const props=PropertiesService.getScriptProperties();const secret=props.getProperty('SHARED_SECRET');if(!secret||data.secret!==secret)throw Error('Solicitud no autorizada.');lock.waitLock(30000);const sheet=SpreadsheetApp.openById(props.getProperty('SHEET_ID')).getSheetByName('Inscripciones');const rows=sheet.getDataRange().getValues();const occupied=rows.slice(1).filter(r=>['reservado','confirmado'].indexOf(r[16])!==-1).length;
if(data.action==='features')return json({ok:true,gifts:true,lookup:true,tickets:true});
if(data.action==='lookup'){const cedula=normalizarCedula(data.cedula);if(!/^\d{5,9}$/.test(cedula))throw Error('Coloca solo los números de tu cédula.');return json({ok:true,tickets:rows.slice(1).filter(r=>normalizarCedula(r[4])===cedula||(esRegalo(r)&&normalizarCedula(r[22])===cedula)).map(cupo)});}
if(data.action==='ticket'){const r=rows.slice(1).find(r=>r[1]===data.id);if(!r||['reservado','confirmado'].indexOf(r[16])===-1)throw Error('El cupo todavía no está aprobado.');return json({ok:true,ticket:cupo(r)});}
if(data.action==='stats')return json({ok:true,percent:Math.min(100,Math.round(occupied/200*100)),soldOut:occupied>=200});
if(data.action==='register'){if(new Date()>=new Date('2026-11-13T19:00:00-04:00'))throw Error('Inscripciones cerradas.');if(occupied>=200)throw Error('Los cupos están agotados.');if(!data.accepted||!data.id||!data.token)throw Error('Datos incompletos.');const safe=v=>{const s=String(v||'');return /^[=+@\-]/.test(s)?"'"+s:s};const total=data.method==='binance'&&data.plan==='full'?90:100;const amount=data.plan==='reserve'?50:total;
const cedula=normalizarCedula(data.cedula);if(!/^\d{5,9}$/.test(cedula))throw Error('Coloca solo los números de tu cédula.');if(data.gift&&String(data.recipientName||'').trim().length<3)throw Error('Indica el nombre completo de quien recibirá el regalo.');if(data.gift&&data.recipientCedula&&!/^\d{5,9}$/.test(String(data.recipientCedula)))throw Error('La cédula del beneficiario debe tener solo números.');if(sheet.getLastColumn()<HEADERS.length)throw Error('Ejecuta actualizarSistema antes de recibir nuevos registros.');
const values=[new Date(),data.id,safe(data.firstName),safe(data.lastName),cedula,safe(data.phone),safe(data.email),data.method,data.plan,total,amount,total-amount,data.rate||'',data.rateDate||'',data.bolivares||'',data.marketing?'si':'no','pendiente_pago','','',data.token,data.gift?'si':'no',data.gift?safe(data.recipientName):'',data.gift?safe(data.recipientCedula):''];sheet.appendRow(values);try{MailApp.sendEmail(MAIL,'Nuevo registro MODO CREADOR · '+data.id,'Nuevo registro pendiente de pago. Revisa la hoja de inscripciones. ID: '+data.id);}catch(err){console.warn('Aviso de correo pendiente: '+err);}return json({ok:true,id:data.id});}
if(data.action==='proof'){const index=rows.findIndex((r,i)=>i>0&&r[1]===data.id&&r[19]===data.token);if(index<1)throw Error('Registro no encontrado.');if(rows[index][16]!=='pendiente_pago')throw Error('Este registro ya tiene un comprobante. Contacta a Mirla para corregirlo.');const types=['image/jpeg','image/png','application/pdf'];if(types.indexOf(data.type)<0)throw Error('Formato no permitido.');const bytes=Utilities.base64Decode(data.base64);if(bytes.length>5242880)throw Error('El archivo supera 5 MB.');const extension=data.type==='application/pdf'?'pdf':data.type==='image/png'?'png':'jpg';const folder=DriveApp.getFolderById(props.getProperty('FOLDER_ID'));const file=folder.createFile(Utilities.newBlob(bytes,data.type,data.id+'.'+extension));const ref=/^[=+@\-]/.test(data.reference)?"'"+data.reference:data.reference;sheet.getRange(index+1,17,1,3).setValues([['en_revision',ref,file.getUrl()]]);try{MailApp.sendEmail(MAIL,'Comprobante recibido · '+data.id,'Revisa el pago en la hoja. ID: '+data.id+'\nComprobante privado: '+file.getUrl());}catch(err){console.warn('Aviso de correo pendiente: '+err);}return json({ok:true,status:'en_revision'});}
throw Error('Acción no disponible.');}catch(err){return json({ok:false,error:err.message});}finally{try{lock.releaseLock();}catch(err){}}}
function json(v){return ContentService.createTextOutput(JSON.stringify(v)).setMimeType(ContentService.MimeType.JSON);}

// Ejecutar UNA VEZ al actualizar; conserva filas, estado, comprobantes y secretos.
function actualizarSistema(){const p=PropertiesService.getScriptProperties();const t=SpreadsheetApp.openById(p.getProperty('SHEET_ID')).getSheetByName('Inscripciones');if(t.getMaxColumns()<HEADERS.length)t.insertColumnsAfter(t.getMaxColumns(),HEADERS.length-t.getMaxColumns());t.getRange(1,1,1,HEADERS.length).setValues([HEADERS]).setFontWeight('bold').setBackground('#7929df').setFontColor('#ffffff');t.hideColumns(20);console.log('Actualización lista: regalos y consulta de cupos habilitados.');}
function normalizarCedula(v){return String(v||'').replace(/^['\s]*[VEve]?[-\s]*/,'').replace(/[.\s-]/g,'');}
function esRegalo(r){return String(r[20]||'').toLowerCase()==='si'&&!!String(r[21]||'').trim();}
function cupo(r){const gift=esRegalo(r);const buyerName=(String(r[2]||'')+' '+String(r[3]||'')).trim().replace(/^'/,'');return {id:String(r[1]),status:String(r[16]),ownerName:gift?String(r[21]).replace(/^'/,''):buyerName,buyerName:buyerName,gift:gift,balance:Number(r[11])||0,currency:r[7]==='binance'?'USDT':'USD a tasa BCV'};}
